### ISSUE TITLE
Obligatory Affixes

### ISSUE THREAD

**Issue by Massemassimo** [aeon0/d4lf#177]
I see no way to add obligatory affixes.
Say for example we look for boots which have to have intelligence, but also movement speed + 1 resistance or 2 resistances.

It could be done using a dedicated tag, something like:

Affixes:
- BootsTest:
      itemType: boots
      minPower: 700
      **obligatory**:
         - [intelligence]
      affixPool:
         - [movement_speed]
         - any_of:
           - [poison_resistance]
           - [cold_resistance]
           - [lightning_resistance]
      minAffixCount: 2

or - using the existing structure - multiple affixPools. 
If the tool would parse multiple affix pools and discard an item as soon as the item does not fit a pool, we could do something like:

Affixes:
- BootsTest:
      itemType: boots
      minPower: 700
      **affixPool:**
         - [intelligence]
      minAffixCount: 1
      **affixPool:**
         - [movement_speed]
         - any_of:
            - [poison_resistance]
            - [cold_resistance]
            - [lightning_resistance]
      minAffixCount: 2

I tried the latter but sadly it does not work, Items fitting the second affix pool are accepted ("greenlit") even if they don't sport intelligence, I guess the program either ignores the first affixpool or greenlights an item as soon as one affixpool fits the item.

**Comment by aeon0** [comment]
I dont really get it because if you want int as mandatory and also movement speed and any resistance you actually saying that movement speed is also mandatory. Thus you need to set the minAffixCount: 3. Or if you say it must have inteligence and either movment speed or any of the resistances, then put movement speed in the any_of block.

```yaml

BootsTest:
  itemType: boots
  minPower: 700  
  affixPool:
    - [intelligence]
    - [movement_speed]
    - any_of:
      - [poison_resistance]
      - [cold_resistance]
      - [lightning_resistance]
  minAffixCount: 3
  
BootsTest2:
  itemType: boots
  minPower: 700  
  affixPool:
    - [intelligence]
    - any_of:
      - [movement_speed]
      - [poison_resistance]
      - [cold_resistance]
      - [lightning_resistance]
  minAffixCount: 2
  ```
