### ISSUE TITLE
Filter fails to detect affixes

### ISSUE THREAD

**Issue by AhmedKazlak** [aeon0/d4lf#203]
Hello, I noticed that the program is not detecting many affixes.

Both critical strikes and overpower should be detected here.
![image](https://github.com/aeon0/d4lf/assets/68192351/10163e7b-6686-453b-9118-c5bababa0b50)

Attack speed should be detected here.
![image](https://github.com/aeon0/d4lf/assets/68192351/2b60a1b1-f29b-4f83-9bcd-0d57816dbb28)

Both movement speed and essence reduction should be detected here.
![image](https://github.com/aeon0/d4lf/assets/68192351/fc08ef18-78bb-44b7-96cd-be1d463c7784)

**Comment by AhmedKazlak** [comment]
Hello, @chrisoro. Thanks for your prompt reply.

1. I am using the latest released version: **4.1.6**

2. I am using a medium font scale on a 2K resolution.
![image](https://github.com/aeon0/d4lf/assets/68192351/c0944b45-c1e9-439b-9a0d-04d8cc0fc6d2)

4. Below is the YAML file.
```
Aspects:
  # General
  - [of_shared_misery, 46]
  - [of_disobedience, 1.0]
  - [ghostwalker, 20]
  - [of_the_umbral, 3]
  # Necromancer
  - [of_grasping_veins, 16]
  - [of_shielding_storm, 4]
  - [bloodbathed, 15, smaller]
  - [of_rathmas_chosen, 45]
  - [of_potent_blood, 16]

Affixes:
  - Chest:
      itemType: [chest armor, pants]
      minPower: 900
      affixPool:
        - [maximum_life]
        - [damage_reduction_from_close_enemies]
        - [damage_reduction]
        - [total_armor]
      minAffixCount: 3

  - Gloves:
      itemType: gloves
      minPower: 900
      affixPool:
        - [attack_speed]
        - [ranks_of_blood_surge]
        - [critical_strike_chance]
        - [overpower_damage]
      minAffixCount: 3

  - Boots:
      itemType: boots
      minPower: 900
      affixPool:
        - [movement_speed]
        - [ranks_of_corpse_tendrils]
        - [essence_cost_reduction]
        - [all_stats]
      minAffixCount: 3

  - Amulet:
      itemType: amulet
      minPower: 900
      affixPool:
        - [cooldown_reduction]
        - [damage_reduction]
        - [total_armor]
        - [essence_cost_reduction]
        - [movement_speed]
        - [ranks_of_the_tides_of_blood_passive]
      minAffixCount: 3

  - Ring:
      itemType: ring
      minPower: 900
      affixPool:
        - [critical_strike_chance]
        - [overpower_damage]
        - [maximum_life]
        - [critical_strike_damage]
      minAffixCount: 3

  - WeaponClose:
      itemType: [dagger, sword, two-handed scythe, scythe, wand]
      minPower: 900
      affixPool:
        - [overpower_damage]
        - [core_skill_damage]
        - [intelligence]
        - [all_stats]
        - [damage_to_close_enemies]
      minAffixCount: 3

  - Shield:
      itemType: shield
      minPower: 900
      affixPool:
        - [maximum_life]
        - [essence_cost_reduction]
        - [cooldown_reduction]
        - [damage_reduction_from_close_enemies]
        - [lucky_hit_up_to_a_chance_to_restore_primary_resource]
        - [lucky_hit_chance]
      minAffixCount: 3

  - Helm:
      itemType: helm
      minPower: 900
      affixPool:
        - [maximum_life]
        - [total_armor]
        - [cooldown_reduction]
        - [willpower]
      minAffixCount: 3
```
