### ISSUE TITLE
Filter junking items incorrectly

### ISSUE THREAD

**Issue by Kiskutnah** [aeon0/d4lf#223]
Heya, this may well be user error, if so, very sorry!

I believe d4lf is junking some items that fit my profile, and can't see any immediate issues with my config that would cause the issue.

![image](https://github.com/aeon0/d4lf/assets/93603273/1d0bdd1f-f3c6-4b34-9f57-5d3186c52271)

![image](https://github.com/aeon0/d4lf/assets/93603273/42ea9403-7a35-4b11-9dd3-658622d01e5f)

these two items I expect to be green instead of red.

I would expect the wand and helm to be green as as they have intelligence and maximum_life, therefore hits the minCount

My profile (C:\Users\user\.d4lf\profiles\shadowNecro.yaml)

```
Affixes:
  - AwesomeHelm:
      itemType: helm
      minPower: 800
      affixPool:
      - count:
            - intelligence
            - cooldown_reduction
            - maximum_life
        minCount: 2
  - AwesomeChestArmor:
      itemType: chest armor
      minPower: 800
      affixPool:
      - count:
            - to_golem_mastery
            - maximum_life
            - armor
        minCount: 2
  - AwesomeGloves:
      itemType: gloves
      minPower: 800
      affixPool:
      - count:
            - to_skeletal_mage_mastery
            - attack_speed
            - critical_strike_chance
        minCount: 2
  - AwesomePants:
      itemType: pants
      minPower: 800
      affixPool:
      - count:
            - to_skeletal_mage_mastery
            - maximum_life
            - dodge_chance
        minCount: 2
  - AwesomeBoots:
      itemType: boots
      minPower: 800
      inherentPool:
      - count:
            - attacks_reduce_evades_cooldown_by_seconds
        minCount: 1
      affixPool:
      - count:
            - intelligence
            - dodge_chance
            - movement_speed
        minCount: 2
  - AwesomeAmulet:
      itemType: amulet
      minPower: 800
      affixPool:
      - count:
            - critical_strike_chance
            - movement_speed
            - to_hellbent_commander
        minCount: 2
  - AwesomeRing:
      itemType: ring
      minPower: 800
      affixPool:
      - count:
            - critical_strike_chance
            - attack_speed
            - maximum_life
        minCount: 2
  - AwesomeWand:
      itemType: wand
      minPower: 800
      affixPool:
      - count:
            - intelligence
            - maximum_life
            - critical_strike_damage
        minCount: 2
  - AwesomeFocus:
      itemType: focus
      minPower: 800
      affixPool:
      - count:
            - critical_strike_chance
            - cooldown_reduction
            - intelligence
        minCount: 2
```

my params.ini 

```
[general]
; Which filter profiles should be run. All .yaml files with "Aspects" and "Affixes" sections will be used from
; config/profiles/*.yaml and C:/Users/USERNAME/.d4lf/profiles/*.yaml
profiles=shadowNecro
; Whether to keep aspects. Can be all, upgrade, none
keep_aspects=upgrade
; Whether to run vision mode on startup or not
run_vision_mode_on_startup=True
; Which tabs to check. Note: All 6 Tabs must be unlocked!
check_chest_tabs=1,2
; Transparancy of the overlay when not hovering it (has a 3 second dealy after hovering)
; The "shown" transparncy is 0.94
hidden_transparency=0.35
; In case you get a warning about the LocalPref file not being found, you can either ignore the warning,
; or specify the correct path for your system here
local_prefs_path=

[char]
; Hotkey to open inventory
inventory=i

[advanced_options]
run_scripts=f9
run_filter=f11
exit_key=f12
log_lvl=info
scripts=vision_mode
process_name=Diablo IV.exe
```
